<?php
/**
 * Author: Nil Portugués Calderó <contact@nilportugues.com>
 * Date: 12/18/15
 * Time: 11:36 PM.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace NilPortugues\SchemaOrg;

use RuntimeException;

/**
 * METHODSTART.
 *
 * @method \NilPortugues\SchemaOrg\Classes\AboutPage aboutPage()
 * @method \NilPortugues\SchemaOrg\Classes\AcceptAction acceptAction()
 * @method \NilPortugues\SchemaOrg\Classes\AccountingService accountingService()
 * @method \NilPortugues\SchemaOrg\Classes\AchieveAction achieveAction()
 * @method \NilPortugues\SchemaOrg\Classes\Action action()
 * @method \NilPortugues\SchemaOrg\Classes\ActionStatusType actionStatusType()
 * @method \NilPortugues\SchemaOrg\Classes\ActivateAction activateAction()
 * @method \NilPortugues\SchemaOrg\Classes\AddAction addAction()
 * @method \NilPortugues\SchemaOrg\Classes\AdministrativeArea administrativeArea()
 * @method \NilPortugues\SchemaOrg\Classes\AdultEntertainment adultEntertainment()
 * @method \NilPortugues\SchemaOrg\Classes\AggregateOffer aggregateOffer()
 * @method \NilPortugues\SchemaOrg\Classes\AggregateRating aggregateRating()
 * @method \NilPortugues\SchemaOrg\Classes\AgreeAction agreeAction()
 * @method \NilPortugues\SchemaOrg\Classes\Airline airline()
 * @method \NilPortugues\SchemaOrg\Classes\Airport airport()
 * @method \NilPortugues\SchemaOrg\Classes\AlignmentObject alignmentObject()
 * @method \NilPortugues\SchemaOrg\Classes\AllocateAction allocateAction()
 * @method \NilPortugues\SchemaOrg\Classes\AmusementPark amusementPark()
 * @method \NilPortugues\SchemaOrg\Classes\AnatomicalStructure anatomicalStructure()
 * @method \NilPortugues\SchemaOrg\Classes\AnatomicalSystem anatomicalSystem()
 * @method \NilPortugues\SchemaOrg\Classes\AnimalShelter animalShelter()
 * @method \NilPortugues\SchemaOrg\Classes\Answer answer()
 * @method \NilPortugues\SchemaOrg\Classes\ApartmentComplex apartmentComplex()
 * @method \NilPortugues\SchemaOrg\Classes\APIReference aPIReference()
 * @method \NilPortugues\SchemaOrg\Classes\AppendAction appendAction()
 * @method \NilPortugues\SchemaOrg\Classes\ApplyAction applyAction()
 * @method \NilPortugues\SchemaOrg\Classes\ApprovedIndication approvedIndication()
 * @method \NilPortugues\SchemaOrg\Classes\Aquarium aquarium()
 * @method \NilPortugues\SchemaOrg\Classes\ArriveAction arriveAction()
 * @method \NilPortugues\SchemaOrg\Classes\Artery artery()
 * @method \NilPortugues\SchemaOrg\Classes\ArtGallery artGallery()
 * @method \NilPortugues\SchemaOrg\Classes\Article article()
 * @method \NilPortugues\SchemaOrg\Classes\AskAction askAction()
 * @method \NilPortugues\SchemaOrg\Classes\AssessAction assessAction()
 * @method \NilPortugues\SchemaOrg\Classes\AssignAction assignAction()
 * @method \NilPortugues\SchemaOrg\Classes\Attorney attorney()
 * @method \NilPortugues\SchemaOrg\Classes\Audience audience()
 * @method \NilPortugues\SchemaOrg\Classes\AudioObject audioObject()
 * @method \NilPortugues\SchemaOrg\Classes\AuthorizeAction authorizeAction()
 * @method \NilPortugues\SchemaOrg\Classes\AutoBodyShop autoBodyShop()
 * @method \NilPortugues\SchemaOrg\Classes\AutoDealer autoDealer()
 * @method \NilPortugues\SchemaOrg\Classes\AutomatedTeller automatedTeller()
 * @method \NilPortugues\SchemaOrg\Classes\AutomotiveBusiness automotiveBusiness()
 * @method \NilPortugues\SchemaOrg\Classes\AutoPartsStore autoPartsStore()
 * @method \NilPortugues\SchemaOrg\Classes\AutoRental autoRental()
 * @method \NilPortugues\SchemaOrg\Classes\AutoRepair autoRepair()
 * @method \NilPortugues\SchemaOrg\Classes\AutoWash autoWash()
 * @method \NilPortugues\SchemaOrg\Classes\Bakery bakery()
 * @method \NilPortugues\SchemaOrg\Classes\BankOrCreditUnion bankOrCreditUnion()
 * @method \NilPortugues\SchemaOrg\Classes\Barcode barcode()
 * @method \NilPortugues\SchemaOrg\Classes\BarOrPub barOrPub()
 * @method \NilPortugues\SchemaOrg\Classes\Beach beach()
 * @method \NilPortugues\SchemaOrg\Classes\BeautySalon beautySalon()
 * @method \NilPortugues\SchemaOrg\Classes\BedAndBreakfast bedAndBreakfast()
 * @method \NilPortugues\SchemaOrg\Classes\BefriendAction befriendAction()
 * @method \NilPortugues\SchemaOrg\Classes\BikeStore bikeStore()
 * @method \NilPortugues\SchemaOrg\Classes\Blog blog()
 * @method \NilPortugues\SchemaOrg\Classes\BlogPosting blogPosting()
 * @method \NilPortugues\SchemaOrg\Classes\BloodTest bloodTest()
 * @method \NilPortugues\SchemaOrg\Classes\BoardingPolicyType boardingPolicyType()
 * @method \NilPortugues\SchemaOrg\Classes\BodyOfWater bodyOfWater()
 * @method \NilPortugues\SchemaOrg\Classes\Bone bone()
 * @method \NilPortugues\SchemaOrg\Classes\BookFormatType bookFormatType()
 * @method \NilPortugues\SchemaOrg\Classes\BookmarkAction bookmarkAction()
 * @method \NilPortugues\SchemaOrg\Classes\Book book()
 * @method \NilPortugues\SchemaOrg\Classes\BookSeries bookSeries()
 * @method \NilPortugues\SchemaOrg\Classes\BookStore bookStore()
 * @method \NilPortugues\SchemaOrg\Classes\Boolean boolean()
 * @method \NilPortugues\SchemaOrg\Classes\BorrowAction borrowAction()
 * @method \NilPortugues\SchemaOrg\Classes\BowlingAlley bowlingAlley()
 * @method \NilPortugues\SchemaOrg\Classes\BrainStructure brainStructure()
 * @method \NilPortugues\SchemaOrg\Classes\Brand brand()
 * @method \NilPortugues\SchemaOrg\Classes\BreadcrumbList breadcrumbList()
 * @method \NilPortugues\SchemaOrg\Classes\Brewery brewery()
 * @method \NilPortugues\SchemaOrg\Classes\Bridge bridge()
 * @method \NilPortugues\SchemaOrg\Classes\BroadcastEvent broadcastEvent()
 * @method \NilPortugues\SchemaOrg\Classes\BroadcastService broadcastService()
 * @method \NilPortugues\SchemaOrg\Classes\BuddhistTemple buddhistTemple()
 * @method \NilPortugues\SchemaOrg\Classes\BusinessAudience businessAudience()
 * @method \NilPortugues\SchemaOrg\Classes\BusinessEntityType businessEntityType()
 * @method \NilPortugues\SchemaOrg\Classes\BusinessEvent businessEvent()
 * @method \NilPortugues\SchemaOrg\Classes\BusinessFunction businessFunction()
 * @method \NilPortugues\SchemaOrg\Classes\BusReservation busReservation()
 * @method \NilPortugues\SchemaOrg\Classes\BusStation busStation()
 * @method \NilPortugues\SchemaOrg\Classes\BusStop busStop()
 * @method \NilPortugues\SchemaOrg\Classes\BusTrip busTrip()
 * @method \NilPortugues\SchemaOrg\Classes\BuyAction buyAction()
 * @method \NilPortugues\SchemaOrg\Classes\CafeOrCoffeeShop cafeOrCoffeeShop()
 * @method \NilPortugues\SchemaOrg\Classes\Campground campground()
 * @method \NilPortugues\SchemaOrg\Classes\Canal canal()
 * @method \NilPortugues\SchemaOrg\Classes\CancelAction cancelAction()
 * @method \NilPortugues\SchemaOrg\Classes\Car car()
 * @method \NilPortugues\SchemaOrg\Classes\CarUsageType carUsageType()
 * @method \NilPortugues\SchemaOrg\Classes\Casino casino()
 * @method \NilPortugues\SchemaOrg\Classes\CatholicChurch catholicChurch()
 * @method \NilPortugues\SchemaOrg\Classes\Cemetery cemetery()
 * @method \NilPortugues\SchemaOrg\Classes\CheckAction checkAction()
 * @method \NilPortugues\SchemaOrg\Classes\CheckInAction checkInAction()
 * @method \NilPortugues\SchemaOrg\Classes\CheckOutAction checkOutAction()
 * @method \NilPortugues\SchemaOrg\Classes\CheckoutPage checkoutPage()
 * @method \NilPortugues\SchemaOrg\Classes\ChildCare childCare()
 * @method \NilPortugues\SchemaOrg\Classes\ChildrensEvent childrensEvent()
 * @method \NilPortugues\SchemaOrg\Classes\ChooseAction chooseAction()
 * @method \NilPortugues\SchemaOrg\Classes\Church church()
 * @method \NilPortugues\SchemaOrg\Classes\CityHall cityHall()
 * @method \NilPortugues\SchemaOrg\Classes\City city()
 * @method \NilPortugues\SchemaOrg\Classes\CivicStructure civicStructure()
 * @method \NilPortugues\SchemaOrg\Classes\Class class()
 * @method \NilPortugues\SchemaOrg\Classes\Clip clip()
 * @method \NilPortugues\SchemaOrg\Classes\ClothingStore clothingStore()
 * @method \NilPortugues\SchemaOrg\Classes\Code code()
 * @method \NilPortugues\SchemaOrg\Classes\CollectionPage collectionPage()
 * @method \NilPortugues\SchemaOrg\Classes\CollegeOrUniversity collegeOrUniversity()
 * @method \NilPortugues\SchemaOrg\Classes\ComedyClub comedyClub()
 * @method \NilPortugues\SchemaOrg\Classes\ComedyEvent comedyEvent()
 * @method \NilPortugues\SchemaOrg\Classes\CommentAction commentAction()
 * @method \NilPortugues\SchemaOrg\Classes\Comment comment()
 * @method \NilPortugues\SchemaOrg\Classes\CommunicateAction communicateAction()
 * @method \NilPortugues\SchemaOrg\Classes\ComputerStore computerStore()
 * @method \NilPortugues\SchemaOrg\Classes\ConfirmAction confirmAction()
 * @method \NilPortugues\SchemaOrg\Classes\ConsumeAction consumeAction()
 * @method \NilPortugues\SchemaOrg\Classes\ContactPage contactPage()
 * @method \NilPortugues\SchemaOrg\Classes\ContactPointOption contactPointOption()
 * @method \NilPortugues\SchemaOrg\Classes\ContactPoint contactPoint()
 * @method \NilPortugues\SchemaOrg\Classes\Continent continent()
 * @method \NilPortugues\SchemaOrg\Classes\ControlAction controlAction()
 * @method \NilPortugues\SchemaOrg\Classes\ConvenienceStore convenienceStore()
 * @method \NilPortugues\SchemaOrg\Classes\CookAction cookAction()
 * @method \NilPortugues\SchemaOrg\Classes\Corporation corporation()
 * @method \NilPortugues\SchemaOrg\Classes\Country country()
 * @method \NilPortugues\SchemaOrg\Classes\Courthouse courthouse()
 * @method \NilPortugues\SchemaOrg\Classes\CreateAction createAction()
 * @method \NilPortugues\SchemaOrg\Classes\CreativeWork creativeWork()
 * @method \NilPortugues\SchemaOrg\Classes\CreativeWorkSeason creativeWorkSeason()
 * @method \NilPortugues\SchemaOrg\Classes\CreativeWorkSeries creativeWorkSeries()
 * @method \NilPortugues\SchemaOrg\Classes\CreditCard creditCard()
 * @method \NilPortugues\SchemaOrg\Classes\Crematorium crematorium()
 * @method \NilPortugues\SchemaOrg\Classes\DanceEvent danceEvent()
 * @method \NilPortugues\SchemaOrg\Classes\DanceGroup danceGroup()
 * @method \NilPortugues\SchemaOrg\Classes\DataCatalog dataCatalog()
 * @method \NilPortugues\SchemaOrg\Classes\DataDownload dataDownload()
 * @method \NilPortugues\SchemaOrg\Classes\DataFeedItem dataFeedItem()
 * @method \NilPortugues\SchemaOrg\Classes\DataFeed dataFeed()
 * @method \NilPortugues\SchemaOrg\Classes\Dataset dataset()
 * @method \NilPortugues\SchemaOrg\Classes\DataType dataType()
 * @method \NilPortugues\SchemaOrg\Classes\Date date()
 * @method \NilPortugues\SchemaOrg\Classes\DateTime dateTime()
 * @method \NilPortugues\SchemaOrg\Classes\DayOfWeek dayOfWeek()
 * @method \NilPortugues\SchemaOrg\Classes\DaySpa daySpa()
 * @method \NilPortugues\SchemaOrg\Classes\DDxElement dDxElement()
 * @method \NilPortugues\SchemaOrg\Classes\DeactivateAction deactivateAction()
 * @method \NilPortugues\SchemaOrg\Classes\DefenceEstablishment defenceEstablishment()
 * @method \NilPortugues\SchemaOrg\Classes\DeleteAction deleteAction()
 * @method \NilPortugues\SchemaOrg\Classes\DeliveryChargeSpecification deliveryChargeSpecification()
 * @method \NilPortugues\SchemaOrg\Classes\DeliveryEvent deliveryEvent()
 * @method \NilPortugues\SchemaOrg\Classes\DeliveryMethod deliveryMethod()
 * @method \NilPortugues\SchemaOrg\Classes\Demand demand()
 * @method \NilPortugues\SchemaOrg\Classes\Dentist dentist()
 * @method \NilPortugues\SchemaOrg\Classes\DepartAction departAction()
 * @method \NilPortugues\SchemaOrg\Classes\DepartmentStore departmentStore()
 * @method \NilPortugues\SchemaOrg\Classes\DiagnosticLab diagnosticLab()
 * @method \NilPortugues\SchemaOrg\Classes\DiagnosticProcedure diagnosticProcedure()
 * @method \NilPortugues\SchemaOrg\Classes\DietarySupplement dietarySupplement()
 * @method \NilPortugues\SchemaOrg\Classes\Diet diet()
 * @method \NilPortugues\SchemaOrg\Classes\DisagreeAction disagreeAction()
 * @method \NilPortugues\SchemaOrg\Classes\DiscoverAction discoverAction()
 * @method \NilPortugues\SchemaOrg\Classes\DiscussionForumPosting discussionForumPosting()
 * @method \NilPortugues\SchemaOrg\Classes\DislikeAction dislikeAction()
 * @method \NilPortugues\SchemaOrg\Classes\Distance distance()
 * @method \NilPortugues\SchemaOrg\Classes\DonateAction donateAction()
 * @method \NilPortugues\SchemaOrg\Classes\DoseSchedule doseSchedule()
 * @method \NilPortugues\SchemaOrg\Classes\DownloadAction downloadAction()
 * @method \NilPortugues\SchemaOrg\Classes\DrawAction drawAction()
 * @method \NilPortugues\SchemaOrg\Classes\DrinkAction drinkAction()
 * @method \NilPortugues\SchemaOrg\Classes\DriveWheelConfigurationValue driveWheelConfigurationValue()
 * @method \NilPortugues\SchemaOrg\Classes\DrugClass drugClass()
 * @method \NilPortugues\SchemaOrg\Classes\DrugCostCategory drugCostCategory()
 * @method \NilPortugues\SchemaOrg\Classes\DrugCost drugCost()
 * @method \NilPortugues\SchemaOrg\Classes\DrugLegalStatus drugLegalStatus()
 * @method \NilPortugues\SchemaOrg\Classes\Drug drug()
 * @method \NilPortugues\SchemaOrg\Classes\DrugPregnancyCategory drugPregnancyCategory()
 * @method \NilPortugues\SchemaOrg\Classes\DrugPrescriptionStatus drugPrescriptionStatus()
 * @method \NilPortugues\SchemaOrg\Classes\DrugStrength drugStrength()
 * @method \NilPortugues\SchemaOrg\Classes\DryCleaningOrLaundry dryCleaningOrLaundry()
 * @method \NilPortugues\SchemaOrg\Classes\Duration duration()
 * @method \NilPortugues\SchemaOrg\Classes\EatAction eatAction()
 * @method \NilPortugues\SchemaOrg\Classes\EducationalAudience educationalAudience()
 * @method \NilPortugues\SchemaOrg\Classes\EducationalOrganization educationalOrganization()
 * @method \NilPortugues\SchemaOrg\Classes\EducationEvent educationEvent()
 * @method \NilPortugues\SchemaOrg\Classes\Electrician electrician()
 * @method \NilPortugues\SchemaOrg\Classes\ElectronicsStore electronicsStore()
 * @method \NilPortugues\SchemaOrg\Classes\ElementarySchool elementarySchool()
 * @method \NilPortugues\SchemaOrg\Classes\EmailMessage emailMessage()
 * @method \NilPortugues\SchemaOrg\Classes\Embassy embassy()
 * @method \NilPortugues\SchemaOrg\Classes\EmergencyService emergencyService()
 * @method \NilPortugues\SchemaOrg\Classes\EmployeeRole employeeRole()
 * @method \NilPortugues\SchemaOrg\Classes\EmploymentAgency employmentAgency()
 * @method \NilPortugues\SchemaOrg\Classes\EndorseAction endorseAction()
 * @method \NilPortugues\SchemaOrg\Classes\Energy energy()
 * @method \NilPortugues\SchemaOrg\Classes\EngineSpecification engineSpecification()
 * @method \NilPortugues\SchemaOrg\Classes\EntertainmentBusiness entertainmentBusiness()
 * @method \NilPortugues\SchemaOrg\Classes\EntryPoint entryPoint()
 * @method \NilPortugues\SchemaOrg\Classes\Enumeration enumeration()
 * @method \NilPortugues\SchemaOrg\Classes\Episode episode()
 * @method \NilPortugues\SchemaOrg\Classes\Event event()
 * @method \NilPortugues\SchemaOrg\Classes\EventReservation eventReservation()
 * @method \NilPortugues\SchemaOrg\Classes\EventStatusType eventStatusType()
 * @method \NilPortugues\SchemaOrg\Classes\EventVenue eventVenue()
 * @method \NilPortugues\SchemaOrg\Classes\ExerciseAction exerciseAction()
 * @method \NilPortugues\SchemaOrg\Classes\ExerciseGym exerciseGym()
 * @method \NilPortugues\SchemaOrg\Classes\ExercisePlan exercisePlan()
 * @method \NilPortugues\SchemaOrg\Classes\ExhibitionEvent exhibitionEvent()
 * @method \NilPortugues\SchemaOrg\Classes\FastFoodRestaurant fastFoodRestaurant()
 * @method \NilPortugues\SchemaOrg\Classes\Festival festival()
 * @method \NilPortugues\SchemaOrg\Classes\FilmAction filmAction()
 * @method \NilPortugues\SchemaOrg\Classes\FinancialService financialService()
 * @method \NilPortugues\SchemaOrg\Classes\FindAction findAction()
 * @method \NilPortugues\SchemaOrg\Classes\FireStation fireStation()
 * @method \NilPortugues\SchemaOrg\Classes\Flight flight()
 * @method \NilPortugues\SchemaOrg\Classes\FlightReservation flightReservation()
 * @method \NilPortugues\SchemaOrg\Classes\Float float()
 * @method \NilPortugues\SchemaOrg\Classes\Florist florist()
 * @method \NilPortugues\SchemaOrg\Classes\FollowAction followAction()
 * @method \NilPortugues\SchemaOrg\Classes\FoodEstablishment foodEstablishment()
 * @method \NilPortugues\SchemaOrg\Classes\FoodEstablishmentReservation foodEstablishmentReservation()
 * @method \NilPortugues\SchemaOrg\Classes\FoodEvent foodEvent()
 * @method \NilPortugues\SchemaOrg\Classes\FurnitureStore furnitureStore()
 * @method \NilPortugues\SchemaOrg\Classes\Game game()
 * @method \NilPortugues\SchemaOrg\Classes\GamePlayMode gamePlayMode()
 * @method \NilPortugues\SchemaOrg\Classes\GameServer gameServer()
 * @method \NilPortugues\SchemaOrg\Classes\GameServerStatus gameServerStatus()
 * @method \NilPortugues\SchemaOrg\Classes\GardenStore gardenStore()
 * @method \NilPortugues\SchemaOrg\Classes\GasStation gasStation()
 * @method \NilPortugues\SchemaOrg\Classes\GatedResidenceCommunity gatedResidenceCommunity()
 * @method \NilPortugues\SchemaOrg\Classes\GeneralContractor generalContractor()
 * @method \NilPortugues\SchemaOrg\Classes\GeoCircle geoCircle()
 * @method \NilPortugues\SchemaOrg\Classes\GeoCoordinates geoCoordinates()
 * @method \NilPortugues\SchemaOrg\Classes\GeoShape geoShape()
 * @method \NilPortugues\SchemaOrg\Classes\GiveAction giveAction()
 * @method \NilPortugues\SchemaOrg\Classes\GolfCourse golfCourse()
 * @method \NilPortugues\SchemaOrg\Classes\GovernmentBuilding governmentBuilding()
 * @method \NilPortugues\SchemaOrg\Classes\GovernmentOffice governmentOffice()
 * @method \NilPortugues\SchemaOrg\Classes\GovernmentOrganization governmentOrganization()
 * @method \NilPortugues\SchemaOrg\Classes\GovernmentPermit governmentPermit()
 * @method \NilPortugues\SchemaOrg\Classes\GovernmentService governmentService()
 * @method \NilPortugues\SchemaOrg\Classes\GroceryStore groceryStore()
 * @method \NilPortugues\SchemaOrg\Classes\HairSalon hairSalon()
 * @method \NilPortugues\SchemaOrg\Classes\HardwareStore hardwareStore()
 * @method \NilPortugues\SchemaOrg\Classes\HealthAndBeautyBusiness healthAndBeautyBusiness()
 * @method \NilPortugues\SchemaOrg\Classes\HealthClub healthClub()
 * @method \NilPortugues\SchemaOrg\Classes\HighSchool highSchool()
 * @method \NilPortugues\SchemaOrg\Classes\HinduTemple hinduTemple()
 * @method \NilPortugues\SchemaOrg\Classes\HobbyShop hobbyShop()
 * @method \NilPortugues\SchemaOrg\Classes\HomeAndConstructionBusiness homeAndConstructionBusiness()
 * @method \NilPortugues\SchemaOrg\Classes\HomeGoodsStore homeGoodsStore()
 * @method \NilPortugues\SchemaOrg\Classes\Hospital hospital()
 * @method \NilPortugues\SchemaOrg\Classes\Hostel hostel()
 * @method \NilPortugues\SchemaOrg\Classes\Hotel hotel()
 * @method \NilPortugues\SchemaOrg\Classes\HousePainter housePainter()
 * @method \NilPortugues\SchemaOrg\Classes\HVACBusiness hVACBusiness()
 * @method \NilPortugues\SchemaOrg\Classes\IceCreamShop iceCreamShop()
 * @method \NilPortugues\SchemaOrg\Classes\IgnoreAction ignoreAction()
 * @method \NilPortugues\SchemaOrg\Classes\ImageGallery imageGallery()
 * @method \NilPortugues\SchemaOrg\Classes\ImageObject imageObject()
 * @method \NilPortugues\SchemaOrg\Classes\ImagingTest imagingTest()
 * @method \NilPortugues\SchemaOrg\Classes\IndividualProduct individualProduct()
 * @method \NilPortugues\SchemaOrg\Classes\InfectiousAgentClass infectiousAgentClass()
 * @method \NilPortugues\SchemaOrg\Classes\InfectiousDisease infectiousDisease()
 * @method \NilPortugues\SchemaOrg\Classes\InformAction informAction()
 * @method \NilPortugues\SchemaOrg\Classes\InsertAction insertAction()
 * @method \NilPortugues\SchemaOrg\Classes\InstallAction installAction()
 * @method \NilPortugues\SchemaOrg\Classes\InsuranceAgency insuranceAgency()
 * @method \NilPortugues\SchemaOrg\Classes\Intangible intangible()
 * @method \NilPortugues\SchemaOrg\Classes\Integer integer()
 * @method \NilPortugues\SchemaOrg\Classes\InteractAction interactAction()
 * @method \NilPortugues\SchemaOrg\Classes\InteractionCounter interactionCounter()
 * @method \NilPortugues\SchemaOrg\Classes\InternetCafe internetCafe()
 * @method \NilPortugues\SchemaOrg\Classes\InviteAction inviteAction()
 * @method \NilPortugues\SchemaOrg\Classes\Invoice invoice()
 * @method \NilPortugues\SchemaOrg\Classes\ItemAvailability itemAvailability()
 * @method \NilPortugues\SchemaOrg\Classes\ItemListOrderType itemListOrderType()
 * @method \NilPortugues\SchemaOrg\Classes\ItemList itemList()
 * @method \NilPortugues\SchemaOrg\Classes\ItemPage itemPage()
 * @method \NilPortugues\SchemaOrg\Classes\JewelryStore jewelryStore()
 * @method \NilPortugues\SchemaOrg\Classes\JobPosting jobPosting()
 * @method \NilPortugues\SchemaOrg\Classes\JoinAction joinAction()
 * @method \NilPortugues\SchemaOrg\Classes\Joint joint()
 * @method \NilPortugues\SchemaOrg\Classes\LakeBodyOfWater lakeBodyOfWater()
 * @method \NilPortugues\SchemaOrg\Classes\Landform landform()
 * @method \NilPortugues\SchemaOrg\Classes\LandmarksOrHistoricalBuildings landmarksOrHistoricalBuildings()
 * @method \NilPortugues\SchemaOrg\Classes\Language language()
 * @method \NilPortugues\SchemaOrg\Classes\LeaveAction leaveAction()
 * @method \NilPortugues\SchemaOrg\Classes\LegalService legalService()
 * @method \NilPortugues\SchemaOrg\Classes\LegislativeBuilding legislativeBuilding()
 * @method \NilPortugues\SchemaOrg\Classes\LendAction lendAction()
 * @method \NilPortugues\SchemaOrg\Classes\Library library()
 * @method \NilPortugues\SchemaOrg\Classes\LifestyleModification lifestyleModification()
 * @method \NilPortugues\SchemaOrg\Classes\Ligament ligament()
 * @method \NilPortugues\SchemaOrg\Classes\LikeAction likeAction()
 * @method \NilPortugues\SchemaOrg\Classes\LiquorStore liquorStore()
 * @method \NilPortugues\SchemaOrg\Classes\ListenAction listenAction()
 * @method \NilPortugues\SchemaOrg\Classes\ListItem listItem()
 * @method \NilPortugues\SchemaOrg\Classes\LiteraryEvent literaryEvent()
 * @method \NilPortugues\SchemaOrg\Classes\LiveBlogPosting liveBlogPosting()
 * @method \NilPortugues\SchemaOrg\Classes\LocalBusiness localBusiness()
 * @method \NilPortugues\SchemaOrg\Classes\LockerDelivery lockerDelivery()
 * @method \NilPortugues\SchemaOrg\Classes\Locksmith locksmith()
 * @method \NilPortugues\SchemaOrg\Classes\LodgingBusiness lodgingBusiness()
 * @method \NilPortugues\SchemaOrg\Classes\LodgingReservation lodgingReservation()
 * @method \NilPortugues\SchemaOrg\Classes\LoseAction loseAction()
 * @method \NilPortugues\SchemaOrg\Classes\LymphaticVessel lymphaticVessel()
 * @method \NilPortugues\SchemaOrg\Classes\MapCategoryType mapCategoryType()
 * @method \NilPortugues\SchemaOrg\Classes\Map map()
 * @method \NilPortugues\SchemaOrg\Classes\MarryAction marryAction()
 * @method \NilPortugues\SchemaOrg\Classes\Mass mass()
 * @method \NilPortugues\SchemaOrg\Classes\MaximumDoseSchedule maximumDoseSchedule()
 * @method \NilPortugues\SchemaOrg\Classes\MediaObject mediaObject()
 * @method \NilPortugues\SchemaOrg\Classes\MedicalAudience medicalAudience()
 * @method \NilPortugues\SchemaOrg\Classes\MedicalCause medicalCause()
 * @method \NilPortugues\SchemaOrg\Classes\MedicalClinic medicalClinic()
 * @method \NilPortugues\SchemaOrg\Classes\MedicalCode medicalCode()
 * @method \NilPortugues\SchemaOrg\Classes\MedicalCondition medicalCondition()
 * @method \NilPortugues\SchemaOrg\Classes\MedicalConditionStage medicalConditionStage()
 * @method \NilPortugues\SchemaOrg\Classes\MedicalContraindication medicalContraindication()
 * @method \NilPortugues\SchemaOrg\Classes\MedicalDevice medicalDevice()
 * @method \NilPortugues\SchemaOrg\Classes\MedicalDevicePurpose medicalDevicePurpose()
 * @method \NilPortugues\SchemaOrg\Classes\MedicalEntity medicalEntity()
 * @method \NilPortugues\SchemaOrg\Classes\MedicalEnumeration medicalEnumeration()
 * @method \NilPortugues\SchemaOrg\Classes\MedicalEvidenceLevel medicalEvidenceLevel()
 * @method \NilPortugues\SchemaOrg\Classes\MedicalGuidelineContraindication medicalGuidelineContraindication()
 * @method \NilPortugues\SchemaOrg\Classes\MedicalGuideline medicalGuideline()
 * @method \NilPortugues\SchemaOrg\Classes\MedicalGuidelineRecommendation medicalGuidelineRecommendation()
 * @method \NilPortugues\SchemaOrg\Classes\MedicalImagingTechnique medicalImagingTechnique()
 * @method \NilPortugues\SchemaOrg\Classes\MedicalIndication medicalIndication()
 * @method \NilPortugues\SchemaOrg\Classes\MedicalIntangible medicalIntangible()
 * @method \NilPortugues\SchemaOrg\Classes\MedicalObservationalStudyDesign medicalObservationalStudyDesign()
 * @method \NilPortugues\SchemaOrg\Classes\MedicalObservationalStudy medicalObservationalStudy()
 * @method \NilPortugues\SchemaOrg\Classes\MedicalOrganization medicalOrganization()
 * @method \NilPortugues\SchemaOrg\Classes\MedicalProcedure medicalProcedure()
 * @method \NilPortugues\SchemaOrg\Classes\MedicalProcedureType medicalProcedureType()
 * @method \NilPortugues\SchemaOrg\Classes\MedicalRiskCalculator medicalRiskCalculator()
 * @method \NilPortugues\SchemaOrg\Classes\MedicalRiskEstimator medicalRiskEstimator()
 * @method \NilPortugues\SchemaOrg\Classes\MedicalRiskFactor medicalRiskFactor()
 * @method \NilPortugues\SchemaOrg\Classes\MedicalRiskScore medicalRiskScore()
 * @method \NilPortugues\SchemaOrg\Classes\MedicalScholarlyArticle medicalScholarlyArticle()
 * @method \NilPortugues\SchemaOrg\Classes\MedicalSignOrSymptom medicalSignOrSymptom()
 * @method \NilPortugues\SchemaOrg\Classes\MedicalSign medicalSign()
 * @method \NilPortugues\SchemaOrg\Classes\MedicalSpecialty medicalSpecialty()
 * @method \NilPortugues\SchemaOrg\Classes\MedicalStudy medicalStudy()
 * @method \NilPortugues\SchemaOrg\Classes\MedicalStudyStatus medicalStudyStatus()
 * @method \NilPortugues\SchemaOrg\Classes\MedicalSymptom medicalSymptom()
 * @method \NilPortugues\SchemaOrg\Classes\MedicalTestPanel medicalTestPanel()
 * @method \NilPortugues\SchemaOrg\Classes\MedicalTest medicalTest()
 * @method \NilPortugues\SchemaOrg\Classes\MedicalTherapy medicalTherapy()
 * @method \NilPortugues\SchemaOrg\Classes\MedicalTrialDesign medicalTrialDesign()
 * @method \NilPortugues\SchemaOrg\Classes\MedicalTrial medicalTrial()
 * @method \NilPortugues\SchemaOrg\Classes\MedicalWebPage medicalWebPage()
 * @method \NilPortugues\SchemaOrg\Classes\MedicineSystem medicineSystem()
 * @method \NilPortugues\SchemaOrg\Classes\MensClothingStore mensClothingStore()
 * @method \NilPortugues\SchemaOrg\Classes\MiddleSchool middleSchool()
 * @method \NilPortugues\SchemaOrg\Classes\MobileApplication mobileApplication()
 * @method \NilPortugues\SchemaOrg\Classes\MobilePhoneStore mobilePhoneStore()
 * @method \NilPortugues\SchemaOrg\Classes\Mosque mosque()
 * @method \NilPortugues\SchemaOrg\Classes\Motel motel()
 * @method \NilPortugues\SchemaOrg\Classes\MotorcycleDealer motorcycleDealer()
 * @method \NilPortugues\SchemaOrg\Classes\MotorcycleRepair motorcycleRepair()
 * @method \NilPortugues\SchemaOrg\Classes\Mountain mountain()
 * @method \NilPortugues\SchemaOrg\Classes\MoveAction moveAction()
 * @method \NilPortugues\SchemaOrg\Classes\MovieClip movieClip()
 * @method \NilPortugues\SchemaOrg\Classes\Movie movie()
 * @method \NilPortugues\SchemaOrg\Classes\MovieRentalStore movieRentalStore()
 * @method \NilPortugues\SchemaOrg\Classes\MovieSeries movieSeries()
 * @method \NilPortugues\SchemaOrg\Classes\MovieTheater movieTheater()
 * @method \NilPortugues\SchemaOrg\Classes\MovingCompany movingCompany()
 * @method \NilPortugues\SchemaOrg\Classes\Muscle muscle()
 * @method \NilPortugues\SchemaOrg\Classes\Museum museum()
 * @method \NilPortugues\SchemaOrg\Classes\MusicAlbum musicAlbum()
 * @method \NilPortugues\SchemaOrg\Classes\MusicEvent musicEvent()
 * @method \NilPortugues\SchemaOrg\Classes\MusicGroup musicGroup()
 * @method \NilPortugues\SchemaOrg\Classes\MusicPlaylist musicPlaylist()
 * @method \NilPortugues\SchemaOrg\Classes\MusicRecording musicRecording()
 * @method \NilPortugues\SchemaOrg\Classes\MusicStore musicStore()
 * @method \NilPortugues\SchemaOrg\Classes\MusicVenue musicVenue()
 * @method \NilPortugues\SchemaOrg\Classes\MusicVideoObject musicVideoObject()
 * @method \NilPortugues\SchemaOrg\Classes\NailSalon nailSalon()
 * @method \NilPortugues\SchemaOrg\Classes\Nerve nerve()
 * @method \NilPortugues\SchemaOrg\Classes\NewsArticle newsArticle()
 * @method \NilPortugues\SchemaOrg\Classes\NGO nGO()
 * @method \NilPortugues\SchemaOrg\Classes\NightClub nightClub()
 * @method \NilPortugues\SchemaOrg\Classes\Notary notary()
 * @method \NilPortugues\SchemaOrg\Classes\Number number()
 * @method \NilPortugues\SchemaOrg\Classes\NutritionInformation nutritionInformation()
 * @method \NilPortugues\SchemaOrg\Classes\OceanBodyOfWater oceanBodyOfWater()
 * @method \NilPortugues\SchemaOrg\Classes\OfferCatalog offerCatalog()
 * @method \NilPortugues\SchemaOrg\Classes\OfferItemCondition offerItemCondition()
 * @method \NilPortugues\SchemaOrg\Classes\Offer offer()
 * @method \NilPortugues\SchemaOrg\Classes\OfficeEquipmentStore officeEquipmentStore()
 * @method \NilPortugues\SchemaOrg\Classes\OnDemandEvent onDemandEvent()
 * @method \NilPortugues\SchemaOrg\Classes\OpeningHoursSpecification openingHoursSpecification()
 * @method \NilPortugues\SchemaOrg\Classes\Optician optician()
 * @method \NilPortugues\SchemaOrg\Classes\OrderAction orderAction()
 * @method \NilPortugues\SchemaOrg\Classes\OrderItem orderItem()
 * @method \NilPortugues\SchemaOrg\Classes\Order order()
 * @method \NilPortugues\SchemaOrg\Classes\OrderStatus orderStatus()
 * @method \NilPortugues\SchemaOrg\Classes\Organization organization()
 * @method \NilPortugues\SchemaOrg\Classes\OrganizationRole organizationRole()
 * @method \NilPortugues\SchemaOrg\Classes\OrganizeAction organizeAction()
 * @method \NilPortugues\SchemaOrg\Classes\OutletStore outletStore()
 * @method \NilPortugues\SchemaOrg\Classes\OwnershipInfo ownershipInfo()
 * @method \NilPortugues\SchemaOrg\Classes\PaintAction paintAction()
 * @method \NilPortugues\SchemaOrg\Classes\Painting painting()
 * @method \NilPortugues\SchemaOrg\Classes\PalliativeProcedure palliativeProcedure()
 * @method \NilPortugues\SchemaOrg\Classes\ParcelDelivery parcelDelivery()
 * @method \NilPortugues\SchemaOrg\Classes\ParcelService parcelService()
 * @method \NilPortugues\SchemaOrg\Classes\ParentAudience parentAudience()
 * @method \NilPortugues\SchemaOrg\Classes\ParkingFacility parkingFacility()
 * @method \NilPortugues\SchemaOrg\Classes\Park park()
 * @method \NilPortugues\SchemaOrg\Classes\PathologyTest pathologyTest()
 * @method \NilPortugues\SchemaOrg\Classes\PawnShop pawnShop()
 * @method \NilPortugues\SchemaOrg\Classes\PayAction payAction()
 * @method \NilPortugues\SchemaOrg\Classes\PaymentChargeSpecification paymentChargeSpecification()
 * @method \NilPortugues\SchemaOrg\Classes\PaymentMethod paymentMethod()
 * @method \NilPortugues\SchemaOrg\Classes\PaymentStatusType paymentStatusType()
 * @method \NilPortugues\SchemaOrg\Classes\PeopleAudience peopleAudience()
 * @method \NilPortugues\SchemaOrg\Classes\PerformAction performAction()
 * @method \NilPortugues\SchemaOrg\Classes\PerformanceRole performanceRole()
 * @method \NilPortugues\SchemaOrg\Classes\PerformingArtsTheater performingArtsTheater()
 * @method \NilPortugues\SchemaOrg\Classes\PerformingGroup performingGroup()
 * @method \NilPortugues\SchemaOrg\Classes\Periodical periodical()
 * @method \NilPortugues\SchemaOrg\Classes\Permit permit()
 * @method \NilPortugues\SchemaOrg\Classes\Person person()
 * @method \NilPortugues\SchemaOrg\Classes\PetStore petStore()
 * @method \NilPortugues\SchemaOrg\Classes\Pharmacy pharmacy()
 * @method \NilPortugues\SchemaOrg\Classes\PhotographAction photographAction()
 * @method \NilPortugues\SchemaOrg\Classes\Photograph photograph()
 * @method \NilPortugues\SchemaOrg\Classes\PhysicalActivityCategory physicalActivityCategory()
 * @method \NilPortugues\SchemaOrg\Classes\PhysicalActivity physicalActivity()
 * @method \NilPortugues\SchemaOrg\Classes\PhysicalExam physicalExam()
 * @method \NilPortugues\SchemaOrg\Classes\PhysicalTherapy physicalTherapy()
 * @method \NilPortugues\SchemaOrg\Classes\Physician physician()
 * @method \NilPortugues\SchemaOrg\Classes\PlaceOfWorship placeOfWorship()
 * @method \NilPortugues\SchemaOrg\Classes\Place place()
 * @method \NilPortugues\SchemaOrg\Classes\PlanAction planAction()
 * @method \NilPortugues\SchemaOrg\Classes\PlayAction playAction()
 * @method \NilPortugues\SchemaOrg\Classes\Playground playground()
 * @method \NilPortugues\SchemaOrg\Classes\Plumber plumber()
 * @method \NilPortugues\SchemaOrg\Classes\PoliceStation policeStation()
 * @method \NilPortugues\SchemaOrg\Classes\Pond pond()
 * @method \NilPortugues\SchemaOrg\Classes\PostalAddress postalAddress()
 * @method \NilPortugues\SchemaOrg\Classes\PostOffice postOffice()
 * @method \NilPortugues\SchemaOrg\Classes\PrependAction prependAction()
 * @method \NilPortugues\SchemaOrg\Classes\Preschool preschool()
 * @method \NilPortugues\SchemaOrg\Classes\PreventionIndication preventionIndication()
 * @method \NilPortugues\SchemaOrg\Classes\PriceSpecification priceSpecification()
 * @method \NilPortugues\SchemaOrg\Classes\ProductModel productModel()
 * @method \NilPortugues\SchemaOrg\Classes\Product product()
 * @method \NilPortugues\SchemaOrg\Classes\ProfessionalService professionalService()
 * @method \NilPortugues\SchemaOrg\Classes\ProfilePage profilePage()
 * @method \NilPortugues\SchemaOrg\Classes\ProgramMembership programMembership()
 * @method \NilPortugues\SchemaOrg\Classes\Property property()
 * @method \NilPortugues\SchemaOrg\Classes\PropertyValue propertyValue()
 * @method \NilPortugues\SchemaOrg\Classes\PropertyValueSpecification propertyValueSpecification()
 * @method \NilPortugues\SchemaOrg\Classes\PsychologicalTreatment psychologicalTreatment()
 * @method \NilPortugues\SchemaOrg\Classes\PublicationEvent publicationEvent()
 * @method \NilPortugues\SchemaOrg\Classes\PublicationIssue publicationIssue()
 * @method \NilPortugues\SchemaOrg\Classes\PublicationVolume publicationVolume()
 * @method \NilPortugues\SchemaOrg\Classes\PublicSwimmingPool publicSwimmingPool()
 * @method \NilPortugues\SchemaOrg\Classes\QAPage qAPage()
 * @method \NilPortugues\SchemaOrg\Classes\QualitativeValue qualitativeValue()
 * @method \NilPortugues\SchemaOrg\Classes\QuantitativeValue quantitativeValue()
 * @method \NilPortugues\SchemaOrg\Classes\Quantity quantity()
 * @method \NilPortugues\SchemaOrg\Classes\Question question()
 * @method \NilPortugues\SchemaOrg\Classes\QuoteAction quoteAction()
 * @method \NilPortugues\SchemaOrg\Classes\RadiationTherapy radiationTherapy()
 * @method \NilPortugues\SchemaOrg\Classes\RadioClip radioClip()
 * @method \NilPortugues\SchemaOrg\Classes\RadioEpisode radioEpisode()
 * @method \NilPortugues\SchemaOrg\Classes\RadioSeason radioSeason()
 * @method \NilPortugues\SchemaOrg\Classes\RadioSeries radioSeries()
 * @method \NilPortugues\SchemaOrg\Classes\RadioStation radioStation()
 * @method \NilPortugues\SchemaOrg\Classes\Rating rating()
 * @method \NilPortugues\SchemaOrg\Classes\ReactAction reactAction()
 * @method \NilPortugues\SchemaOrg\Classes\ReadAction readAction()
 * @method \NilPortugues\SchemaOrg\Classes\RealEstateAgent realEstateAgent()
 * @method \NilPortugues\SchemaOrg\Classes\ReceiveAction receiveAction()
 * @method \NilPortugues\SchemaOrg\Classes\Recipe recipe()
 * @method \NilPortugues\SchemaOrg\Classes\RecommendedDoseSchedule recommendedDoseSchedule()
 * @method \NilPortugues\SchemaOrg\Classes\RecyclingCenter recyclingCenter()
 * @method \NilPortugues\SchemaOrg\Classes\RegisterAction registerAction()
 * @method \NilPortugues\SchemaOrg\Classes\RejectAction rejectAction()
 * @method \NilPortugues\SchemaOrg\Classes\RentAction rentAction()
 * @method \NilPortugues\SchemaOrg\Classes\RentalCarReservation rentalCarReservation()
 * @method \NilPortugues\SchemaOrg\Classes\ReplaceAction replaceAction()
 * @method \NilPortugues\SchemaOrg\Classes\ReplyAction replyAction()
 * @method \NilPortugues\SchemaOrg\Classes\ReportedDoseSchedule reportedDoseSchedule()
 * @method \NilPortugues\SchemaOrg\Classes\Report report()
 * @method \NilPortugues\SchemaOrg\Classes\ReservationPackage reservationPackage()
 * @method \NilPortugues\SchemaOrg\Classes\Reservation reservation()
 * @method \NilPortugues\SchemaOrg\Classes\ReservationStatusType reservationStatusType()
 * @method \NilPortugues\SchemaOrg\Classes\ReserveAction reserveAction()
 * @method \NilPortugues\SchemaOrg\Classes\Reservoir reservoir()
 * @method \NilPortugues\SchemaOrg\Classes\Residence residence()
 * @method \NilPortugues\SchemaOrg\Classes\Restaurant restaurant()
 * @method \NilPortugues\SchemaOrg\Classes\ResumeAction resumeAction()
 * @method \NilPortugues\SchemaOrg\Classes\ReturnAction returnAction()
 * @method \NilPortugues\SchemaOrg\Classes\ReviewAction reviewAction()
 * @method \NilPortugues\SchemaOrg\Classes\Review review()
 * @method \NilPortugues\SchemaOrg\Classes\RiverBodyOfWater riverBodyOfWater()
 * @method \NilPortugues\SchemaOrg\Classes\Role role()
 * @method \NilPortugues\SchemaOrg\Classes\RoofingContractor roofingContractor()
 * @method \NilPortugues\SchemaOrg\Classes\RsvpAction rsvpAction()
 * @method \NilPortugues\SchemaOrg\Classes\RsvpResponseType rsvpResponseType()
 * @method \NilPortugues\SchemaOrg\Classes\RVPark rVPark()
 * @method \NilPortugues\SchemaOrg\Classes\SaleEvent saleEvent()
 * @method \NilPortugues\SchemaOrg\Classes\ScheduleAction scheduleAction()
 * @method \NilPortugues\SchemaOrg\Classes\ScholarlyArticle scholarlyArticle()
 * @method \NilPortugues\SchemaOrg\Classes\School school()
 * @method \NilPortugues\SchemaOrg\Classes\ScreeningEvent screeningEvent()
 * @method \NilPortugues\SchemaOrg\Classes\Sculpture sculpture()
 * @method \NilPortugues\SchemaOrg\Classes\SeaBodyOfWater seaBodyOfWater()
 * @method \NilPortugues\SchemaOrg\Classes\SearchAction searchAction()
 * @method \NilPortugues\SchemaOrg\Classes\SearchResultsPage searchResultsPage()
 * @method \NilPortugues\SchemaOrg\Classes\Season season()
 * @method \NilPortugues\SchemaOrg\Classes\Seat seat()
 * @method \NilPortugues\SchemaOrg\Classes\SelfStorage selfStorage()
 * @method \NilPortugues\SchemaOrg\Classes\SellAction sellAction()
 * @method \NilPortugues\SchemaOrg\Classes\SendAction sendAction()
 * @method \NilPortugues\SchemaOrg\Classes\Series series()
 * @method \NilPortugues\SchemaOrg\Classes\ServiceChannel serviceChannel()
 * @method \NilPortugues\SchemaOrg\Classes\Service service()
 * @method \NilPortugues\SchemaOrg\Classes\ShareAction shareAction()
 * @method \NilPortugues\SchemaOrg\Classes\ShoeStore shoeStore()
 * @method \NilPortugues\SchemaOrg\Classes\ShoppingCenter shoppingCenter()
 * @method \NilPortugues\SchemaOrg\Classes\SingleFamilyResidence singleFamilyResidence()
 * @method \NilPortugues\SchemaOrg\Classes\SiteNavigationElement siteNavigationElement()
 * @method \NilPortugues\SchemaOrg\Classes\SkiResort skiResort()
 * @method \NilPortugues\SchemaOrg\Classes\SocialEvent socialEvent()
 * @method \NilPortugues\SchemaOrg\Classes\SocialMediaPosting socialMediaPosting()
 * @method \NilPortugues\SchemaOrg\Classes\SoftwareApplication softwareApplication()
 * @method \NilPortugues\SchemaOrg\Classes\SoftwareSourceCode softwareSourceCode()
 * @method \NilPortugues\SchemaOrg\Classes\SomeProducts someProducts()
 * @method \NilPortugues\SchemaOrg\Classes\Specialty specialty()
 * @method \NilPortugues\SchemaOrg\Classes\SportingGoodsStore sportingGoodsStore()
 * @method \NilPortugues\SchemaOrg\Classes\SportsActivityLocation sportsActivityLocation()
 * @method \NilPortugues\SchemaOrg\Classes\SportsClub sportsClub()
 * @method \NilPortugues\SchemaOrg\Classes\SportsEvent sportsEvent()
 * @method \NilPortugues\SchemaOrg\Classes\SportsTeam sportsTeam()
 * @method \NilPortugues\SchemaOrg\Classes\StadiumOrArena stadiumOrArena()
 * @method \NilPortugues\SchemaOrg\Classes\State state()
 * @method \NilPortugues\SchemaOrg\Classes\SteeringPositionValue steeringPositionValue()
 * @method \NilPortugues\SchemaOrg\Classes\Store store()
 * @method \NilPortugues\SchemaOrg\Classes\StructuredValue structuredValue()
 * @method \NilPortugues\SchemaOrg\Classes\SubscribeAction subscribeAction()
 * @method \NilPortugues\SchemaOrg\Classes\SubwayStation subwayStation()
 * @method \NilPortugues\SchemaOrg\Classes\SuperficialAnatomy superficialAnatomy()
 * @method \NilPortugues\SchemaOrg\Classes\SuspendAction suspendAction()
 * @method \NilPortugues\SchemaOrg\Classes\Synagogue synagogue()
 * @method \NilPortugues\SchemaOrg\Classes\Table table()
 * @method \NilPortugues\SchemaOrg\Classes\TakeAction takeAction()
 * @method \NilPortugues\SchemaOrg\Classes\TattooParlor tattooParlor()
 * @method \NilPortugues\SchemaOrg\Classes\Taxi taxi()
 * @method \NilPortugues\SchemaOrg\Classes\TaxiReservation taxiReservation()
 * @method \NilPortugues\SchemaOrg\Classes\TaxiService taxiService()
 * @method \NilPortugues\SchemaOrg\Classes\TaxiStand taxiStand()
 * @method \NilPortugues\SchemaOrg\Classes\TechArticle techArticle()
 * @method \NilPortugues\SchemaOrg\Classes\TelevisionStation televisionStation()
 * @method \NilPortugues\SchemaOrg\Classes\TennisComplex tennisComplex()
 * @method \NilPortugues\SchemaOrg\Classes\Text text()
 * @method \NilPortugues\SchemaOrg\Classes\TheaterEvent theaterEvent()
 * @method \NilPortugues\SchemaOrg\Classes\TheaterGroup theaterGroup()
 * @method \NilPortugues\SchemaOrg\Classes\TherapeuticProcedure therapeuticProcedure()
 * @method \NilPortugues\SchemaOrg\Classes\Thing thing()
 * @method \NilPortugues\SchemaOrg\Classes\Ticket ticket()
 * @method \NilPortugues\SchemaOrg\Classes\TieAction tieAction()
 * @method \NilPortugues\SchemaOrg\Classes\TipAction tipAction()
 * @method \NilPortugues\SchemaOrg\Classes\TireShop tireShop()
 * @method \NilPortugues\SchemaOrg\Classes\TouristAttraction touristAttraction()
 * @method \NilPortugues\SchemaOrg\Classes\TouristInformationCenter touristInformationCenter()
 * @method \NilPortugues\SchemaOrg\Classes\ToyStore toyStore()
 * @method \NilPortugues\SchemaOrg\Classes\TrackAction trackAction()
 * @method \NilPortugues\SchemaOrg\Classes\TradeAction tradeAction()
 * @method \NilPortugues\SchemaOrg\Classes\TrainReservation trainReservation()
 * @method \NilPortugues\SchemaOrg\Classes\TrainStation trainStation()
 * @method \NilPortugues\SchemaOrg\Classes\TrainTrip trainTrip()
 * @method \NilPortugues\SchemaOrg\Classes\TransferAction transferAction()
 * @method \NilPortugues\SchemaOrg\Classes\TravelAction travelAction()
 * @method \NilPortugues\SchemaOrg\Classes\TravelAgency travelAgency()
 * @method \NilPortugues\SchemaOrg\Classes\TreatmentIndication treatmentIndication()
 * @method \NilPortugues\SchemaOrg\Classes\TVClip tVClip()
 * @method \NilPortugues\SchemaOrg\Classes\TVEpisode tVEpisode()
 * @method \NilPortugues\SchemaOrg\Classes\TVSeason tVSeason()
 * @method \NilPortugues\SchemaOrg\Classes\TVSeries tVSeries()
 * @method \NilPortugues\SchemaOrg\Classes\TypeAndQuantityNode typeAndQuantityNode()
 * @method \NilPortugues\SchemaOrg\Classes\UnitPriceSpecification unitPriceSpecification()
 * @method \NilPortugues\SchemaOrg\Classes\UnRegisterAction unRegisterAction()
 * @method \NilPortugues\SchemaOrg\Classes\UpdateAction updateAction()
 * @method \NilPortugues\SchemaOrg\Classes\URL URL()
 * @method \NilPortugues\SchemaOrg\Classes\UseAction useAction()
 * @method \NilPortugues\SchemaOrg\Classes\UserBlocks userBlocks()
 * @method \NilPortugues\SchemaOrg\Classes\UserCheckins userCheckins()
 * @method \NilPortugues\SchemaOrg\Classes\UserComments userComments()
 * @method \NilPortugues\SchemaOrg\Classes\UserDownloads userDownloads()
 * @method \NilPortugues\SchemaOrg\Classes\UserInteraction userInteraction()
 * @method \NilPortugues\SchemaOrg\Classes\UserLikes userLikes()
 * @method \NilPortugues\SchemaOrg\Classes\UserPageVisits userPageVisits()
 * @method \NilPortugues\SchemaOrg\Classes\UserPlays userPlays()
 * @method \NilPortugues\SchemaOrg\Classes\UserPlusOnes userPlusOnes()
 * @method \NilPortugues\SchemaOrg\Classes\UserTweets userTweets()
 * @method \NilPortugues\SchemaOrg\Classes\Vehicle vehicle()
 * @method \NilPortugues\SchemaOrg\Classes\Vein vein()
 * @method \NilPortugues\SchemaOrg\Classes\Vessel vessel()
 * @method \NilPortugues\SchemaOrg\Classes\VeterinaryCare veterinaryCare()
 * @method \NilPortugues\SchemaOrg\Classes\VideoGallery videoGallery()
 * @method \NilPortugues\SchemaOrg\Classes\VideoGameClip videoGameClip()
 * @method \NilPortugues\SchemaOrg\Classes\VideoGame videoGame()
 * @method \NilPortugues\SchemaOrg\Classes\VideoGameSeries videoGameSeries()
 * @method \NilPortugues\SchemaOrg\Classes\VideoObject videoObject()
 * @method \NilPortugues\SchemaOrg\Classes\ViewAction viewAction()
 * @method \NilPortugues\SchemaOrg\Classes\VisualArtsEvent visualArtsEvent()
 * @method \NilPortugues\SchemaOrg\Classes\VisualArtwork visualArtwork()
 * @method \NilPortugues\SchemaOrg\Classes\Volcano volcano()
 * @method \NilPortugues\SchemaOrg\Classes\VoteAction voteAction()
 * @method \NilPortugues\SchemaOrg\Classes\WantAction wantAction()
 * @method \NilPortugues\SchemaOrg\Classes\WarrantyPromise warrantyPromise()
 * @method \NilPortugues\SchemaOrg\Classes\WarrantyScope warrantyScope()
 * @method \NilPortugues\SchemaOrg\Classes\WatchAction watchAction()
 * @method \NilPortugues\SchemaOrg\Classes\Waterfall waterfall()
 * @method \NilPortugues\SchemaOrg\Classes\WearAction wearAction()
 * @method \NilPortugues\SchemaOrg\Classes\WebApplication webApplication()
 * @method \NilPortugues\SchemaOrg\Classes\WebPageElement webPageElement()
 * @method \NilPortugues\SchemaOrg\Classes\WebPage webPage()
 * @method \NilPortugues\SchemaOrg\Classes\WebSite webSite()
 * @method \NilPortugues\SchemaOrg\Classes\WholesaleStore wholesaleStore()
 * @method \NilPortugues\SchemaOrg\Classes\WinAction winAction()
 * @method \NilPortugues\SchemaOrg\Classes\Winery winery()
 * @method \NilPortugues\SchemaOrg\Classes\WPAdBlock wPAdBlock()
 * @method \NilPortugues\SchemaOrg\Classes\WPFooter wPFooter()
 * @method \NilPortugues\SchemaOrg\Classes\WPHeader wPHeader()
 * @method \NilPortugues\SchemaOrg\Classes\WPSideBar wPSideBar()
 * @method \NilPortugues\SchemaOrg\Classes\WriteAction writeAction()
 * @method \NilPortugues\SchemaOrg\Classes\Zoo zoo()
 * METHODEND
 */
class SchemaOrg
{
    /**
     * @var self
     */
    private static $instance;

    /**
     * @var array
     */
    private static $instances = [];

    /**
     * @param $method
     * @param $args
     *
     * @throws RuntimeException
     *
     * @return mixed
     */
    public function __call($method, $args)
    {
        $name = $method;
        $name[0] = strtoupper($name[0]);

        if (class_exists('NilPortugues\\SchemaOrg\\Classes\\'.$name, true)) {
            if (empty(self::$instances[$name])) {
                $class = 'NilPortugues\\SchemaOrg\\Classes\\'.$name;
                self::$instances[$name] = new $class();
            }

            return self::$instances[$name];
        }

        throw new RuntimeException(sprintf('Method %s does not exist.', $name));
    }

    /**
     * @return SchemaOrg
     */
    public static function schemas()
    {
        if (null === self::$instance) {
            self::$instance = new self();
        }

        return self::$instance;
    }

    /**
     * Protected constructor to prevent creating a new instance of the
     * *Singleton* via the `new` operator from outside of this class.
     */
    protected function __construct()
    {
    }

    /**
     * Private clone method to prevent cloning of the instance of the
     * *Singleton* instance.
     *
     * @codeCoverageIgnore
     */
    private function __clone()
    {
    }

    /**
     * Private unserialize method to prevent unserializing of the *Singleton*
     * instance.
     *
     * @codeCoverageIgnore
     */
    private function __wakeup()
    {
    }
}
